layout_spectrum: 0.06099806
typography_spectrum: 0.8175731
color:
  saturation: 0.7132961
  lightness: 0.1959195
  brandStrength: 0.4849619
  rhythmicContrast: 0.8632648
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Lo comunic
